/**:
    ros__parameters:
        image_transport: raw    # image format
        family: Standard41h12           # tag family name
        size: 0.076             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 2.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: 1           # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: 0            # write additional debugging images to current working directory

        # optional list of tags
        tag:
            ids: [378, 14]            # tag ID
            frames: [plant_pot1, pot2]  # optional frame name
            sizes: [0.076, 0.162]   # optional tag-specific edge size
